# Site settings
title: 波引自动化
SEOTitle: 波引自动化 | Boyin Automation
email: wtango@hotmail.com
description: ""
keyword: ""
url: "http://wtango.github.io"              # your host, for absolute URL
baseurl: "/boyin"         # for example, '/blog' if your blog hosted on 'host/blog'


# Default settings for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important